// Generated by gencpp from file swarm_msgs/GlobalExtrinsicStatus.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_GLOBALEXTRINSICSTATUS_H
#define SWARM_MSGS_MESSAGE_GLOBALEXTRINSICSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <swarm_msgs/GlobalExtrinsic.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct GlobalExtrinsicStatus_
{
  typedef GlobalExtrinsicStatus_<ContainerAllocator> Type;

  GlobalExtrinsicStatus_()
    : header()
    , drone_id(0)
    , extrinsic()  {
    }
  GlobalExtrinsicStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drone_id(0)
    , extrinsic(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _drone_id_type;
  _drone_id_type drone_id;

   typedef std::vector< ::swarm_msgs::GlobalExtrinsic_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_msgs::GlobalExtrinsic_<ContainerAllocator> >> _extrinsic_type;
  _extrinsic_type extrinsic;





  typedef boost::shared_ptr< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> const> ConstPtr;

}; // struct GlobalExtrinsicStatus_

typedef ::swarm_msgs::GlobalExtrinsicStatus_<std::allocator<void> > GlobalExtrinsicStatus;

typedef boost::shared_ptr< ::swarm_msgs::GlobalExtrinsicStatus > GlobalExtrinsicStatusPtr;
typedef boost::shared_ptr< ::swarm_msgs::GlobalExtrinsicStatus const> GlobalExtrinsicStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator1> & lhs, const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drone_id == rhs.drone_id &&
    lhs.extrinsic == rhs.extrinsic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator1> & lhs, const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0b0c9dc59b0fab5523a56f1f276faa9";
  }

  static const char* value(const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0b0c9dc59b0fab5ULL;
  static const uint64_t static_value2 = 0x523a56f1f276faa9ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/GlobalExtrinsicStatus";
  }

  static const char* value(const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 drone_id\n"
"GlobalExtrinsic[] extrinsic    # global extrinsic with other drones\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: swarm_msgs/GlobalExtrinsic\n"
"# GlobalExtrinsic.msg\n"
"uint8 teammate_id # The drone_id of teammates\n"
"float32[3] rot_deg\n"
"float32[3] trans\n"
;
  }

  static const char* value(const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drone_id);
      stream.next(m.extrinsic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GlobalExtrinsicStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::GlobalExtrinsicStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drone_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "extrinsic[]" << std::endl;
    for (size_t i = 0; i < v.extrinsic.size(); ++i)
    {
      s << indent << "  extrinsic[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::swarm_msgs::GlobalExtrinsic_<ContainerAllocator> >::stream(s, indent + "    ", v.extrinsic[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_GLOBALEXTRINSICSTATUS_H
