(cl:defpackage swarm_msgs-msg
  (:use )
  (:export
   "<GLOBALEXTRINSIC>"
   "GLOBALEXTRINSIC"
   "<GLOBALEXTRINSICSTATUS>"
   "GLOBALEXTRINSICSTATUS"
   "<OBSERVETEAMMATE>"
   "OBSERVETEAMMATE"
   "<QUADSTATEPUB>"
   "QUADSTATEPUB"
   "<TEAMSTATUS>"
   "TEAMSTATUS"
   "<TEAMMATEINFO>"
   "TEAMMATEINFO"
  ))

