# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_msgs/GlobalExtrinsicStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import swarm_msgs.msg

class GlobalExtrinsicStatus(genpy.Message):
  _md5sum = "d0b0c9dc59b0fab5523a56f1f276faa9"
  _type = "swarm_msgs/GlobalExtrinsicStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
uint8 drone_id
GlobalExtrinsic[] extrinsic    # global extrinsic with other drones
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: swarm_msgs/GlobalExtrinsic
# GlobalExtrinsic.msg
uint8 teammate_id # The drone_id of teammates
float32[3] rot_deg
float32[3] trans"""
  __slots__ = ['header','drone_id','extrinsic']
  _slot_types = ['std_msgs/Header','uint8','swarm_msgs/GlobalExtrinsic[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,drone_id,extrinsic

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GlobalExtrinsicStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.drone_id is None:
        self.drone_id = 0
      if self.extrinsic is None:
        self.extrinsic = []
    else:
      self.header = std_msgs.msg.Header()
      self.drone_id = 0
      self.extrinsic = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.drone_id
      buff.write(_get_struct_B().pack(_x))
      length = len(self.extrinsic)
      buff.write(_struct_I.pack(length))
      for val1 in self.extrinsic:
        _x = val1.teammate_id
        buff.write(_get_struct_B().pack(_x))
        buff.write(_get_struct_3f().pack(*val1.rot_deg))
        buff.write(_get_struct_3f().pack(*val1.trans))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.extrinsic is None:
        self.extrinsic = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.drone_id,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.extrinsic = []
      for i in range(0, length):
        val1 = swarm_msgs.msg.GlobalExtrinsic()
        start = end
        end += 1
        (val1.teammate_id,) = _get_struct_B().unpack(str[start:end])
        start = end
        end += 12
        val1.rot_deg = _get_struct_3f().unpack(str[start:end])
        start = end
        end += 12
        val1.trans = _get_struct_3f().unpack(str[start:end])
        self.extrinsic.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.drone_id
      buff.write(_get_struct_B().pack(_x))
      length = len(self.extrinsic)
      buff.write(_struct_I.pack(length))
      for val1 in self.extrinsic:
        _x = val1.teammate_id
        buff.write(_get_struct_B().pack(_x))
        buff.write(val1.rot_deg.tostring())
        buff.write(val1.trans.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.extrinsic is None:
        self.extrinsic = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.drone_id,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.extrinsic = []
      for i in range(0, length):
        val1 = swarm_msgs.msg.GlobalExtrinsic()
        start = end
        end += 1
        (val1.teammate_id,) = _get_struct_B().unpack(str[start:end])
        start = end
        end += 12
        val1.rot_deg = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
        start = end
        end += 12
        val1.trans = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
        self.extrinsic.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
