# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_msgs/GlobalExtrinsic.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GlobalExtrinsic(genpy.Message):
  _md5sum = "1a76ac5934d5f766451f12a662f47943"
  _type = "swarm_msgs/GlobalExtrinsic"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# GlobalExtrinsic.msg
uint8 teammate_id # The drone_id of teammates
float32[3] rot_deg
float32[3] trans"""
  __slots__ = ['teammate_id','rot_deg','trans']
  _slot_types = ['uint8','float32[3]','float32[3]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       teammate_id,rot_deg,trans

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GlobalExtrinsic, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.teammate_id is None:
        self.teammate_id = 0
      if self.rot_deg is None:
        self.rot_deg = [0.] * 3
      if self.trans is None:
        self.trans = [0.] * 3
    else:
      self.teammate_id = 0
      self.rot_deg = [0.] * 3
      self.trans = [0.] * 3

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.teammate_id
      buff.write(_get_struct_B().pack(_x))
      buff.write(_get_struct_3f().pack(*self.rot_deg))
      buff.write(_get_struct_3f().pack(*self.trans))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.teammate_id,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 12
      self.rot_deg = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.trans = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.teammate_id
      buff.write(_get_struct_B().pack(_x))
      buff.write(self.rot_deg.tostring())
      buff.write(self.trans.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.teammate_id,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 12
      self.rot_deg = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.trans = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
